# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_signup_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('expires_timestamp', models.DateTimeField()),
            ],
        ),
    ]
