# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_auto_20151223_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='username',
            field=models.CharField(default='alex', max_length=100, unique=True),
        ),
    ]
