# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20160101_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='expires_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
