# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0007_auto_20160101_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDayEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('birth_days_emailed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
