# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_auto_20160102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayemails',
            name='birth_days_emailed',
            field=models.BooleanField(default='False'),
        ),
    ]
