# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_apisession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiSession',
            new_name='ApiUser',
        ),
    ]
