# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_apiuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
